common:
    arch: fishnet99
    workers: 1
    batch_size: 32

    max_iter: 500000
    policy: "step"
    base_lr: 0.1
    lr_steps: [150000, 300000, 450000]
    lr_mults: [0.1, 0.1, 0.1]
    momentum: 0.9
    weight_decay: 0.0001

    print_freq: 10
    save_path: checkpoints/fishnet99_bs256